### ISSUE TITLE
GNOME 3 : Standby wird nicht verhindert.

### ISSUE THREAD

**Issue by almereyda** [xaverW/MediathekView#12]
Ähnlich dem Spielen eines Filmes, bspw. mit VLC, könnte es in manchen Situationen wünschenswert erscheinen, wenn während des Downloads der Standby Modus verhindert würde.

**Comment by criztovyl** [comment]
http://java-gnome.sourceforge.net/doc/api/4.1/org/gnome/gtk/ApplicationInhibitFlags.html

**Comment by xaverW** [comment]
wird wohl nicht kommen, es gibt mehrere BS und Umgebungen in denen das Programm läuft. Kann da nicht für jedes Extras einbauen.
