### ISSUE TITLE
Java 1.6 statt 1.7 ausreichend?

### ISSUE THREAD

**Issue by jonasstein** [xaverW/MediathekView#25]
Unter gentoo Linux konnte ich mit virtual/jdk (1.6)  1.6.0-r2 MediathekView keine Probleme finden. Ist 1.7 notwendig, oder könnte man in den Abhängigkeiten auf 1.6 herabsetzen?

Vielen Dank für das ausgezeichnete Programm

**Comment by genodeftest** [comment]
Falls du OpenJDK oder die JRE von Sun/Oracle verwendest, solltest du aus Sicherheitsgründen auf keinen Fall mehr die veraltete Version 1.6 einsetzen. Da sind einige kritische Lücken drin, die wohl dazu geeignet wären, über z.B. manipulierte Downloads deinen Rechner zu übernehmen.
