### ISSUE TITLE
Ist das JSON?

### ISSUE THREAD

**Issue by ratopi** [xaverW/MediathekView#27]
Wie ich sehe wird die Filmliste inzwischen in JSON-Syntax abgespeichert.  Allerdings frage ich mich, ob das wirklich ein sinnvolles JSON ist.
Das JSON-Objekt besitzt lediglich zwei Attribute "Filmliste" und "X".  Mit einem "normalen" JSON-Parser wird man dann auch nur ein Objekt zurückbekommen mit zwei Attributen oder sogar einen Fehler.
Bei dem Datenkonstrukt das ihr abspeichern wollt, handelt es sich doch vielmehr um eine zweidimensionale Liste (Liste in Liste).
Daher möchte ich einen Gegenvorschlag machen.  Wie wäre es mit folgender Datenstruktur (als Skizze):
    {
      "meta": [ "13.01.2015, 07:11", "13.01.2015, 06:11", "3", "MSearch [Rel: 399] - Compile", .... ]
      "columns": [ "Sender", "Thema", "Titel", "Datum", "Zeit", .... ],
      "data": [
          [ "3Sat", "3sat", "Schmitz' Mama", "11.01.2015", "20:15:00", "00:59:03", "1043", .... ],
          [ "", "", "Eisenbahn-Romantik: Nächtlicher Blick auf Virginias Bahnen", "12.01.2015", ... ]
          ...
      ]
    }

**Comment by xaverW** [comment]
die Diskussion gabs sschon:
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1348

**Comment by dr0i** [comment]
Leider ist der link tot. Die Diskussion hätte mich auch interessiert ...
