### ISSUE TITLE
Kann keine Filme aus der GUI steamen

### ISSUE THREAD

**Issue by daedadu** [xaverW/MediathekView#28]
Ich hab hier nen Ubuntu Rechner

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

mit 
OpenJDK 64Bit- Server VM
Version 1.7.0.75
Runtimeversion 1.7.0_75-b13

Mediathekview [Buildnummer 8.060]

der keine Videos startet weil er mit Fehlermeldungen im Terminal abbricht.
VLC ist installiert, wenn man den Link direkt in VLC eingibt geht auch alles

. ---------------------------------------
. | Film abspielen
. | URL: http://nrodl.zdf.de/none/3sat/15/01/150127_amazonien1_ard_2256k_p14v11.mp4
. | Startzeit: 22:30:33
. | Programmaufruf:  http://nrodl.zdf.de/none/3sat/15/01/150127_amazonien1_ard_2256k_p14v11.mp4 --play-and-exit
. ---------------------------------------
java.io.IOException: Cannot run program "http://nrodl.zdf.de/none/3sat/15/01/150127_amazonien1_ard_2256k_p14v11.mp4": error=2, No suc$
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:450)
        at java.lang.Runtime.exec(Runtime.java:347)
        at mediathek.controller.starter.RuntimeExec.exec(RuntimeExec.java:68)
        at mediathek.controller.starter.StarterClass$ExternalProgramDownloadThread.starten(StarterClass.java:544)
        at mediathek.controller.starter.StarterClass$ExternalProgramDownloadThread.run(StarterClass.java:433)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 6 more

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* Fehlernr: 450028932
* Exception: Cannot run program "http://nrodl.zdf.de/none/3sat/15/01/150127_amazonien1_ard_2256k_p14v11.mp4": error=2, No such file o$
* Fehler(MediathekView): RuntimeExec.exec
*           Fehler beim Starten

. ---------------------------------------
. | Film fertig
. | Startzeit: 22:30:33
. | Endzeit: 22:30:33
. | Dauer: 0 s
. | Dauer: <1 Min.
. | URL: http://nrodl.zdf.de/none/3sat/15/01/150127_amazonien1_ard_2256k_p14v11.mp4
. | Programmaufruf:  http://nrodl.zdf.de/none/3sat/15/01/150127_amazonien1_ard_2256k_p14v11.mp4 --play-and-exit
. ---------------------------------------

Ne Ahnung wor das liegen könnte?

**Comment by daedadu** [comment]
Ok ist behoben "Wenn nichts geht" hat mich erhellt, habe auf Standardeinstellungen zurueckgestellt

**Comment by claell** [comment]
Ich vermute mal, dass mit deinen Sets (abspielen) etwas nicht in Ordnung war. Aber schön, dass es auch so geklappt hat.

**Comment by xaverW** [comment]
Hallo,


> Ich vermute mal, dass mit deinen Sets (abspielen) etwas nicht in
> Ordnung war. Aber schön, dass es auch so geklappt hat.


. | Programmaufruf:
http://nrodl.zdf.de/none/3sat/15/01/150127_amazonien1_ard_2256k_p14v11.mp4
--play-and-exit

das war das Problem, da hat "vlc" gefehlt, da wurde die URL direkt als
"Programm" aufgerufen. Mit einem "Reset" wurden die Standardsets wieder
hergestellt.

Grüße
Xaver





Am Wed, 28 Jan 2015 13:37:52 -0800
schrieb daedadu <notifications@github.com>:
