### ISSUE TITLE
Keine Git-Tags für Releases?

### ISSUE THREAD

**Issue by hartwork** [xaverW/MediathekView#29]
Hallo!

Gibt es einen bestimmten Grund, warum es hier keine Git-Tags für Releases gibt?
Sonst +1 von mir für Release-Tags.

Danke, Sebastian

**Comment by xaverW** [comment]
bemühe mich, sie nicht zu vergessen :)

**Comment by hartwork** [comment]
Das Ticket ist zu, aber es gibt keine Tags? Hast du vergessen, sie zu pushen?
