### ISSUE TITLE
MediathekView 10 (Linux) won't start with LookAndFeel GTK

### ISSUE THREAD

**Issue by genodeftest** [xaverW/MediathekView#37]
I am running Fedora 21 x86_64.

Steps to reproduce:
1. start MediathekView
2. open preferences, change LookAndFeel to GTK
3. close MediathekView
4. start MediathekView

What happens:
MediathekView stops loading while displaying "GUI initialisieren" on the splash screen. It does not abort but keeps waiting forever.

What should happen:
MediathekView should run fine with GTK LookAndFeel

**Comment by xaverW** [comment]
it works now

**Comment by genodeftest** [comment]
Confirmed. Thanks!

There is a small issue left: After following the steps 1 through 4 from above, the preferences window does not list the GTK LookAndFeel, instead the field is empty.
