### ISSUE TITLE
Zielpfad in Abos nicht funktional und nicht dokumentiert

### ISSUE THREAD

**Issue by COLABORATI** [xaverW/MediathekView#39]
Im Einstellungsdialog für ein Abo gibt es das Eingabefeld "Zielpfad" - diese Einstellung wird jedoch ignoriert, zumindest ist das meine Interpretation. Ich habe hier "ordner-fuer-abo" eingegeben und hatte erwartet, dass die zum Abo gehörenden Videos in einem Unterordner "ordner-fuer-abo" des im Programmset eingestellten Zielordners landen, was nicht der Fall war.

Daraufhin habe ich zum Testen ein neues Abo angelegt und in dieses Feld einen absoluten Pfad eingegeben, also z.B. "/home/user/videos/ordner-fuer-abo" - der Download wurde jedoch in dem vom Programmset vorgegebenen Pfad  abgelegt.

Möglicherweise handelt es sich um ein Missverständnis, aber leider ist genau diese Einstellung nicht dokumentiert (oder ich konnte nichts finden, hab aber in der Anleitung gesucht). Ich hatte erwartet, dass man hier die Einstellungen des Zielpfades aus dem Programmset überschreiben ("overriden") kann.

Falls das nicht der Fall ist - wofür ist dieses Feld gedacht? 

Und eigentlich will ich wissen: wie kann ich Dateien aus einem Abo in einem eigenen Ordner sammeln, das kann auch ein Unterordner des im Programmset angegebenen Pfades sein. 

Momentan behelfe ich mir, indem ich für jedes Abo ein eigenes Programmset anlege, was etwas umständlich ist und zu einer unübersichtlichen Anzahl von Programmsets führen kann. 

Danke für die Aufmerksamkeit!

**Comment by xaverW** [comment]
Hallo,

im Set muss unter "Speicherziel" "Unterordner mit Thema anlegen"
angeklickt sein. Als Standard wird das Thema der Sendungen verwendet.
Das kann man im Abo "überschreiben" mit einem beliebigen Namen.
Ist die Checkbox nicht aktiviert, wird alles direkt im Pfad
des Sets gespeichert.

Absolute Pfade kann man im Abo nicht anlegen.

Grüße





Am Mon, 30 Mar 2015 06:45:34 -0700
schrieb COLABORATI <notifications@github.com>:

**Comment by COLABORATI** [comment]
Danke für die schnelle Antwort. 

OK, diese Option war mir bekannt, allerdings will ich Leerzeichen und Umlaute im Namen des enstehenden Ordners vermeiden. Auch aus anderen Gründen wäre es klasse, wenn man Abos optional in einen separaten Ordner speichern könnte (z.B. "meine_abos", "deine_abos" usw.).

Und wozu dient dann die Eingabemöglichkeit "Zielpfad" im Eigenschaften-Dialog eines Abos?

Abgesehen davon ond etwas OT, aber muss mal sein: vielen Dank für MV, absolutes Spitzenprogramm!!!

**Comment by claell** [comment]
Es gibt doch bei Mediathekview eine Option, Leerzeichen und Umlaute zu ersetzen. Das funktioniert dann auch bei den Abo-Ordnern, soweit ich weiß.

**Comment by xaverW** [comment]
Hi,

-> Leerzeichen: in den Einstellungen kann man unter
"Aufzeichnen...->Datei- und Pfad..." Einstellungen vornehmen. zB.
Leerzeichen durch "_" ersetzen.

Die Verbotenen Zeichen des jeweiligen BS werden immer ersetzt.

Das bezieht sich auch auf Pfadnamen.


->eigener Unterordner Abo: Der Unterordner "Thema" kann durch einen
"Zielpfad" im Abo überschrieben werden. Es wird dann nicht das "Thema"
sondern der "Zielpfad" des Abos als Unterordner des Downloadpfades
verwendet. Wenn du das änderst, musst du die Downloads
"Auffrischen" (Button mit den 2 Pfeilen), dann werden die Downloads mit
den neuen Einstellungen neu angelegt.

Grüße
Xaver





Am Mon, 30 Mar 2015 09:00:07 -0700
schrieb Claudius Ellsel <notifications@github.com>:

**Comment by COLABORATI** [comment]
OK, die Ersetzungen hab ich auch gesehen, geht auch für Pfade, super.

Auf die Gefahr hin, das ich nerve: was genau bewirkt denn nun das Einstellungsfeld "Zielpfad" in den Einstellungen für das Abo? Reine Neugier jetzt...

**Comment by claell** [comment]
Zielpfad legt den Ordnernamen des Abos fest

**Comment by xaverW** [comment]
Hi,

auf die Gefahr hin, dass ich mich wiederhole :)

> ->eigener Unterordner Abo: Der Unterordner "Thema" kann durch einen  
> "Zielpfad" im Abo überschrieben werden. Es wird dann nicht das "Thema"
> sondern der "Zielpfad" des Abos als Unterordner des Downloadpfades
> verwendet. Wenn du das änderst, musst du die Downloads
> "Auffrischen" (Button mit den 2 Pfeilen), dann werden die Downloads
> mit den neuen Einstellungen neu angelegt.


ist das Feld "Zielfpad" leer, wird das Thema als Unterordner verwendet.
Ist ein "Zeilpfad" angegeben, wird "Zielpfad" für den Unterordner
verwendet.

Damit kannst du also deine unterschiedlichen Pfade für die Abos
realisieren: "meinAbo", "deinAbo", ...





Am Mon, 30 Mar 2015 10:20:18 -0700
schrieb COLABORATI <notifications@github.com>:

**Comment by xaverW** [comment]
habe ich jetzt zu spät gesehen, genau so ist es.



Am Mon, 30 Mar 2015 10:34:51 -0700
schrieb Claudius Ellsel <notifications@github.com>:

**Comment by COLABORATI** [comment]
Ich lach mich weg, sorry, heute ist der Nachmittags-Kaffee ausgefallen, man merkt es sofort. Alles klar jetzt, danke nochmals für die Aufmerksamkeit!

**Comment by COLABORATI** [comment]
Noch eine Ergänzung: die von Dir so präzise formulierte Beschreibung war ja genau das Stück Information, das mir fehlte, der Zusammenhang zu der Unterordner-Einstellung im Set war mir nicht klar. Evtl. wäre hier ein Hinweis im GUI sinnvoll, so wie Du es geschrieben hattest passt es wahrscheinlich auch noch in den Einstellungsdialog für die Abos, z.B.:

_Zielpfad wird nur überschrieben, wenn im Set unter "Speicherziel" "Unterordner mit Thema anlegen" aktiviert ist!_

In der Anleitung wäre der richtige Platz dafür wahrscheinlich nach dem ersten Absatz unter der Zwischenüberschrift "Abos anpassen oder ausschalten sowie Herunterladen von abonnierten Sendungen":

_Ein anderer Zielordner wird nur benutzt, wenn im zugehörigen Set unter "Speicherziel" die Option "Unterordner mit Thema anlegen" (Checkbox) aktiviert ist!_

Wenn die Anleitung hier bei github wäre, hätte ich es natürlich schon selber eingefügt und einen PR geschickt :)

Schönen Abend noch!
