### ISSUE TITLE
Geschwindigkeit aufrunden und nicht abrunden

### ISSUE THREAD

**Issue by alexkli** [xaverW/MediathekView#41]
Die Geschwindigkeitsanzeige bei den Downloads rundet momentan auf die nächste Minute ab, d.h. wenn es noch 1 Min 50 Sekunden dauert, wird 1 Minute angezeigt, und man sich dann wundert, wenn es doch noch länger dauert :)

Lieber sollte dann 2 Min angezeigt werden, etwas zu viel und dann schneller fertig sein ist besser für die UX. Unter 1 Minute wird ja auch "< 1 Min." angezeigt.

Die Abrundung findet anscheinend hier statt durch eine Integer Division: https://github.com/xaverW/MediathekView/blob/master/src/mediathek/daten/DatenDownload.java#L356

Das hier sollte es tun: `Long.toString( Math.ceil((double)start.restSekunden / 60.0) )`

**Comment by claell** [comment]
Dann würde nur niemals "1 Minute" angezeigt. Also evtl. Immer mit "<", z.B. "< 2 Min.", "< 3Min." usw. anzeigen?

**Comment by xaverW** [comment]
danke, habe es jetzt so gemacht:
return Long.toString(Math.round(start.restSekunden / 60.0)) + " Min.";

**Comment by alexkli** [comment]
Math.round rundet aber kaufmännisch, was dann bei 1:29 noch 1 Minute anzeigt und damit 1/3 falsch liegt. Zu optimistische Progressbars sind für den User sehr nervig.

@claell es wird ja immer noch "< 1 Min" angezeigt. Immer "<" davor packen ist nicht so praktisch, bei längeren Zeiten (noch 40 Min z.B.) ist das eher verwirrend. Vielleicht zeigt man ab 1 Minuten die Sekunden an.

**Comment by xaverW** [comment]
Math.round rundet aber kaufmännisch: Ja, so wars gedacht.

Vielleicht zeigt man ab 1 Minuten die Sekunden: keine gute Idee, da die Anzeige dann springt, so genau ist die Vorhersage nicht.

Habe die letzten 5 Minuten nocht etwas angepsst.

**Comment by claell** [comment]
@alexkli Ja, ist nur evtl. auch verwirrend, wenn nach "2 Min" auf einmal "< 1 Min" statt nur "1 Min" angezeigt wird, bin aber auf dem Gebiet nicht bewandert, nur meine Überlegung dazu.

@xaverW Springt beim Runden die Anzeige dann nicht auch, wenn die Zeit im kritischen Bereich zwischen auf- und abrunden ist?

**Comment by xaverW** [comment]
die Anzeige springt beim Runden auch aber nur beim Wechsel von einer zur anderen Minute und nicht bei jeder Sekunde.
die aktuelle Anzeige ist: "30 s", "1 Min", "2 Min" ... 
denk dass das so schon passt

**Comment by claell** [comment]
Ja, das meinte ich. Aber wenn das nicht stört ist ja alles in Ordnung. Ich wäre dann mit der Lösung zufrieden.

**Comment by alexkli** [comment]
Sieht gut aus.
