### ISSUE TITLE
Filmliste context menu (right-click): show complete set of download Urls

### ISSUE THREAD

**Issue by Wikinaut** [xaverW/MediathekView#45]
#### Problem
When you have a movie like ARTE "Bob Dylan No Direction Home" (08.08.2015) which is offered in three or more resolutions, the context menu still only allows to copy the "in HD" and "in Klein" kopieren (whatever "Klein" means, the word is a different issue).

#### Suggestion
I suggest to modify the context menu, or even make it adapting to the movie item, so that the urls for **all** available resolutions are listed.

As an ad-hoc alternative, change the the download window (the window, where the users selects one of the resolutions for downloading) so that it lists the Urls in addition to the present selection radio buttons.

**Comment by xaverW** [comment]
it offers all available resolutions

Film-URL kopieren
 -> in "HD" kopieren
 -> in "Klein" kopieren





Am Sun, 09 Aug 2015 02:51:30 -0700
schrieb Wikinaut <notifications@github.com>:

**Comment by Wikinaut** [comment]
No, the current context menu does *not* offer all three resolutions of that movie, see screenshot

<img src="https://i.imgur.com/TRWliLv.png">

**Comment by xaverW** [comment]
1. Film-URL kopieren ---> is the normal resolution
2.  -> in "HD" kopieren ---> is HD
3.  -> in "Klein" kopieren ----> is smaller then the normal resolution






Am Sun, 09 Aug 2015 03:09:53 -0700
schrieb Wikinaut <notifications@github.com>:

**Comment by Wikinaut** [comment]
Uh, then I suggest now

#### change

this to a layout which makes this clear:

```
Film-URL kopieren:
-> "geringe" Auflösung
-> "mittlere" Auflösung
-> "HD" Auflösung
```

The first entry *von mir aus* being still linked to medium resolution.

**Comment by xaverW** [comment]
the "normal" resolution is the best who is not HD,

HD is HD and "klein" ist smaller than the "normal" resolution. Every sender has
other resolutions, so there is no "standard" what these exact means
(only HD is, what it says)

"Film-URL kopieren" is the normal resolution and exist for every film, the other are
optional, that's the reason for the list-sorting.






Am Sun, 09 Aug 2015 03:21:40 -0700
schrieb Wikinaut <notifications@github.com>:

**Comment by xaverW** [comment]
better?

Am Sun, 09 Aug 2015 03:21:40 -0700
schrieb Wikinaut <notifications@github.com>:

**Comment by Wikinaut** [comment]
"hoher" vs. "HD" vs. "Klein" -- das passt nicht zusammen.

Was soll das großgeschriebene "Klein" bedeuten?
Was soll "HD" (High Definition = "hohe(!) Auflösung") im Gegensatz zu "hoher" ?

Also ich schlage nochmal vor, die Auflösungen eindeutig zu benennen, und die (drei) Texte in einheitlicher Schreibweise zu drucken.  

```
Film-URL kopieren:
-> URL für geringe Auflösung
-> URL für mittlere Auflösung
-> URL für HD-Auflösung
```

**Comment by Wikinaut** [comment]
solved via https://github.com/xaverW/MediathekView/commit/abc02cfc8d8a8434ab32b57ab2ae3674d90f9754 . Danke! Bitcoin Donations an welche Adresse?
