### ISSUE TITLE
Download menu: instead of radio button (one of many), allow selection of several download resolutions at once

### ISSUE THREAD

**Issue by Wikinaut** [xaverW/MediathekView#46]
Sometimes I wish to select more than a single resolution for download, for example, I want to download the medium and the high resolution.

This can currently not be selected.

#### Suggestion
I suggest to redesign the download selection so that users can select more than one resolution for the download scheduler.

**Comment by xaverW** [comment]
in this case, you need also different names/folders
so, the way now is, to start a second download with the
other resolution, I don't think, I will change this.




Am Sun, 09 Aug 2015 02:53:24 -0700
schrieb Wikinaut <notifications@github.com>:

**Comment by Wikinaut** [comment]
The filenames will be different due to the different hashes, numbers of the Mediathek providers - all fies have different names already when downloading, I don't see much trouble with the names.

However, it may be programmatically difficult to enqueue more than one download from the one download window.

**Comment by claell** [comment]
The problem is that there are options to set a file name that does not have hashes anymore. So then there would be files with the same name.

**Comment by Wikinaut** [comment]
@claell adding _low _medium , or _high  or _S, _M, XL, or _SD, _MD, _HD, _HQ  to the filename (example filename_HD.mp4) ?

**Comment by claell** [comment]
Yes that would have to be done in this case.

**Comment by xaverW** [comment]
you complicate the normal way for a few times you need 2 formats instead of a second klick for the second download.

I wont change this.
