### ISSUE TITLE
ServusTV Download?

### ISSUE THREAD

**Issue by z3ntu** [xaverW/MediathekView#49]
Wäre das möglich?

**Comment by xaverW** [comment]
nein

http://sourceforge.net/p/zdfmediathk/wiki/FAQ/#wird-das-programm-um-die-mediathek-des-senders-xyz-erweitert

**Comment by z3ntu** [comment]
Die URL lässt sich auslesen...
Aber naja, schade. Wäre sehr angenehm gewesen :/

**Comment by claell** [comment]
Warum keine Privaten Sender? Aus Prinzip?

**Comment by xaverW** [comment]
Am Tue, 18 Aug 2015 11:38:09 -0700
schrieb Claudius Ellsel <notifications@github.com>:

> Warum keine Privaten Sender? Aus Prinzip?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/xaverW/MediathekView/issues/49#issuecomment-132312580


ja

**Comment by claell** [comment]
Alles klar, kann ich ein wenig verstehen.
