### ISSUE TITLE
Remove hardcoded `shutdown -h now` for shutdown after finished and allow custom commands

### ISSUE THREAD

**Issue by dsohler** [xaverW/MediathekView#52]
Due to the fact most Linux distributions moved from SysVinit to systemd there isn’t a `shutdown -h now` command available, because there is no initscripts and thus no `shutdown` binary.

Some desktop environments also provide an own shutdown tool.

Instead of adding an option for every shutdown mechanism or hardcoding an (now) outdated one implement an option to define your own shutdown command (or more generally a command that can be executed after all downloads are done).

**Comment by xaverW** [comment]
habe es jetzt so erweitert, dass im Ordner bin ein "shutdown.sh"
Skript liegt, das den Shutdown-Befehl enthält, es wird aufgerufen und
kann auch vom Benutzer geändert werden.

**Comment by dsohler** [comment]
Welchen Ordner `bin` meinst du? in `~/.mediathek3` ist jedenfalls keiner. In `/opt/mediathek` ist einer (jedenfalls beim Installationspaket für meine Distribution), aber dort sollte aus Updategründen nichts vom User geändert werden (und entsprechende Berechtigung besteht ja eh nicht).

Meiner Meinung nach wäre es besser, den hardgecodeten Shutdown-Befehl durch eine Konfigurationsoption zu ersetzen, statt ihn (aus Usersicht und updateunfreundlich) einfach hardgecodet auszulagern.

**Comment by xaverW** [comment]
die Pakete der Distris sind nicht von mir
ich mein den Ordner, ist so auch im zipfile:

https://github.com/xaverW/MediathekView/tree/master/dist/bin

**Comment by dsohler** [comment]
Ja, die Pakete sind nicht von dir, stimmt. Dennoch: Dass User auf irgendetwas außerhalb ihres Homeverzeichnisses schreibend zugreifen können, ist selbst unter Windows inzwischen eher unüblich.

Was spricht gegen eine Option, anstatt den unveränderlichen Befehl einfach woanders im (Regelfall unveränderlich) auszulagern, und zudem noch Updates schwerer zu machen? (Die Datei wird beim Update ja überschrieben.)

**Comment by xaverW** [comment]
habe es geändert, kann jetzt in den Einstellungen vorgegeben werden.


Am Sun, 20 Sep 2015 10:48:23 -0700
schrieb Dirk <notifications@github.com>:

**Comment by claell** [comment]
Top, ist dann auf jeden Fall sehr zukunftssicher und variabel.

**Comment by dsohler** [comment]
Jo, das klingt genau so, wie es sein sollte :smile: :+1:
