### ISSUE TITLE
[Enhancement] Add public radio podcast

### ISSUE THREAD

**Issue by 5TDg9** [xaverW/MediathekView#53]
Hi xaverW,

great work!

So far, i'm just missing the possibility to download radio podcasts aswell.
A great repository with a full list of __radio__ podcasts can be found here: http://www.podcast.de
The also offer an API (https://api.podcast.de), but unfortunately limited to request a maximum of 200 results.

Another even better repository also offers an API: 
http://gpoddernet.readthedocs.org/en/latest/api/integration.html
http://gpodder.org is a great open source project!
I would love to see an application that merges the features of both: MediathekView & gpodder :+1:

**Comment by xaverW** [comment]
http://sourceforge.net/p/zdfmediathk/wiki/FAQ/#wird-das-programm-um-die-mediathek-des-senders-xyz-erweitert

only "Öffentlich-Rechtliches Fernsehen"
