### ISSUE TITLE
put files into a folder within the distribution package 

### ISSUE THREAD

**Issue by voxspox** [xaverW/MediathekView#55]
Concerning the distribution package like MediathekView_10.zip, I suggest to put all the files into a folder. This folder is named according to the software version. This is common practice and come in handy p.ex. when installing the software to /opt

**Comment by xaverW** [comment]
i think about it

**Comment by jonasstein** [comment]
I am interested in this too. This bug was closed without a result. Are there any news? 
Best wishes,
JS

**Comment by xaverW** [comment]
this ist not a bug!
Ist a wish to do this in a other way and i said: I think about it
