### ISSUE TITLE
List Itemes overlay when scrolling - Graphics Bug?

### ISSUE THREAD

**Issue by criztovyl** [xaverW/MediathekView#56]
Hello,
when I'm using MediathekView on Debian Jessie and scroll down the list, the list items overlay like this:
![bildschirmfoto von 2015-11-03 19 11 31](https://cloud.githubusercontent.com/assets/2174918/10916992/bd4c7090-825e-11e5-93e8-0e6e8c5e2641.png)
Details:
    
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux 8.2 (jessie)
    Release:	8.2
    Codename:	jessie

    $ uname -a
    Linux [hostname] 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux

    $ java -version
    java version "1.7.0_79"
    OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
    OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by criztovyl** [comment]
I've tested both MediatheView from debian repositories and the downloaded file.

**Comment by criztovyl** [comment]
Found an Exception raised if overlay happens:
http://pastebin.com/iiH9NzBH

**Comment by xaverW** [comment]
have you tried it, with these installation:
http://sourceforge.net/p/zdfmediathk/wiki/Linux/#debian-8-gnome
or do you use debian-libs?
I have tried it, and did not get these error.

**Comment by criztovyl** [comment]
Installed it via apt-get but also ran it from the downloaded file. (Without the menu stuff)
I also experience some graphics bugs when I run freemind where i.e. text overlays when/after moving the map around.
Maybe it has to to something with my graphics card and java, i.e I can't use any "better" (proprietary) driver as that breaks my complete system.

    $ dpkg -l | grep "VLC\|flvstreamer\|libav-tools"
    ii  flvstreamer                           2.1c1-1                                amd64        command-line RTMP client
    ii  libvlccore8                           2.2.1-5+b1                             amd64        base library for VLC and its modules
    ii  vlc-data                              2.2.1-5                                all          Common data for VLC
    ii  vlc-plugin-notify                     2.2.1-5+b1                             amd64        LibNotify plugin for VLC
    ii  vlc-plugin-samba                      2.2.1-5+b1                             amd64        Samba plugin for VLC

**Comment by criztovyl** [comment]
Also after some clicking around, I found out that there is no overlay when I select 1-day-range. With 2-day-range overlaying happens only when I'm scrolling through elements of the second day. Sometimes there is also no overlay when I use "new only" and/or "HD only"
