### ISSUE TITLE
no Install doc for the repository code

### ISSUE THREAD

**Issue by buhtz** [xaverW/MediathekView#57]
There is no documentation in the repository(!) about how to install the software.

Currently I am using version 4 on Ubuntu 14.04 which is quite outdated. Before I open a lot of Issues here I will check how the current version on GitHub works. But I don't know how to install that.

**Comment by claell** [comment]
Here is a documentation and download link of the program: http://zdfmediathk.sourceforge.net/

**Comment by buhtz** [comment]
Behind the links is only the project website. You should use the possibilities of HyperText and give a full link. [This](https://sourceforge.net/p/zdfmediathk/wiki/Linux/#installation) would be the correct link.

I would propose that you decide between SF or GitHub. Having only one would lower the support workload.

On GitHub it is usual to have a `README.md` in the root directory of the repository. In their you can describe everything (Usage, Installation, Contact, ...) what is needed or _link_ to the sections on another website (e.g. your SF page).

**Comment by xaverW** [comment]
Das ist die Website des Projekts:

http://sourceforge.net/projects/zdfmediathk/


wenn du im Programm im Menü "Hilfe->Hilfe und Fragen ..." öffnest,
findest du Links zu den Websiten des Programms (Forum, Anleitung,
Download, ..). Dort ist dann github erst verlinkt! Wenn du
Github/Mediathek gefunden hast, wirst du auch die Websiten des
Programms finden.

Und bevor die Frage noch kommt: im Ordner "dist" (daraus wird das
zip-file für den Programmdownload): da gibts einen Ordner Info mit
einer README.txt in der steht das wichtigste (wo ist das wiki,
Installation, Start, Build).

Könnte man eigentlich finden, auch wenn man von Hinten zu Suchen
anfängt.




 


Am Mon, 30 Nov 2015 00:55:17 -0800
schrieb buhtz <notifications@github.com>:

**Comment by buhtz** [comment]
On 2015-11-30 04:10 xaverW <notifications@github.com> wrote:
> einer README.txt in der steht das wichtigste (wo ist das wiki,
> Installation, Start, Build).

In das root-Directory gehört eine "README.md", das ist Konvention bei
GitHub und erwartet jeder User auch so. Das ist immer der Einstieg zur
Doku.

Existiert die nicht, gibt es auch keine Doku. Zum Suchen ist meine Zeit
zu schade bzw. die Nutzenmotivation zu niedrig.

Du möchtest ja auch, dass andere am Projekt partizipieren, Code,
Bug-Reports, Reviews etc beisteuern. Deswegen solltest du die
Zugangsschwelle für "Contributoren" niedrig halten.
Dazu gehört auch Englisch zu schreiben, damit die gesamte Community
folgen kann.
-- 
GnuPGP-Key ID 0751A8EC

**Comment by xaverW** [comment]
Am Mon, 30 Nov 2015 12:20:52 -0800
schrieb buhtz <notifications@github.com>:

> On 2015-11-30 04:10 xaverW <notifications@github.com> wrote:
> > einer README.txt in der steht das wichtigste (wo ist das wiki,
> > Installation, Start, Build).  
> 
> In das root-Directory gehört eine "README.md", das ist Konvention bei
> GitHub und erwartet jeder User auch so. Das ist immer der Einstieg zur
> Doku.
> 


nochmal: Die Startseite des Projekts ist die:
http://sourceforge.net/projects/zdfmediathk/

die ist im Programm verlinkt, die findet man über Google, die ist in
Zeitschriften verlinkt, Downloadportalen, ..

darüber findet man alles was du suchst
Wenn du von hinten anfängst, musst du ein wenig suchen, sollte aber
auch zu schaffen sein.


> Zum Suchen ist meine
> Zeit zu schade bzw. die Nutzenmotivation zu niedrig.

und die neunmalklugen Kommentare zu beantworten, ist mir meine Zeit zu
schade.



> Dazu gehört auch Englisch zu schreiben, damit die gesamte Community
> folgen kann.

das Programm bietet "DEUTSCHES" Fernsehen an??? Und du hast es ja
verstanden!
