### ISSUE TITLE
[Suggestion] Add MediathekView as Addon for OSMC/KODI

### ISSUE THREAD

**Issue by Wikinaut** [xaverW/MediathekView#60]
Running OSMC ( https://osmc.tv/download/ ) on my RaspberryPi (1 and 2), I deeply missing MediathekView's feature there to _download_ videos from Mediathek.

If you see a chance to develop an AddOn (for OSMC), that would be great (I will send you some mBTC then).

At the moment I do not see any way to actually _download_ a stream I watch via an OSMC AddOn.

**Comment by claell** [comment]
Do you want the complete functionality for OSMC or only parts? The normal program UI is rather designed for mouse and keyboard.

**Comment by Wikinaut** [comment]
It would be sufficient (as a starting point), to have a kind of "context menu entry": "record this stream".

I mean this:

Users have already some Addons activated (e.g. "Mediathek", "ARTE+7"). - so the selection possibility using the different "mediatheks" is present, but missing is a "record" (= download) function.

I offer you 0,25 BTC (or 100 Euros) for implementation of the "download the selected movie to the SD card" feature.


Of course, if we can have the MediathekView "select from all xx.xxx available movies" catalogue feature in OSMC on the Raspi, this would be fantastic (I promise you some additional mBTC for this then).

**Comment by Wikinaut** [comment]
regarding the UI: using the free KORI App, you don't need the mouse+keyboard.

**Comment by Wikinaut** [comment]
https://play.google.com/store/apps/details?id=org.xbmc.kore KORE

**Comment by claell** [comment]
Ok, so you basically want an addon for Kodi, got it now.

**Comment by claell** [comment]
So having an extra entry to download a movie is rather easy I guess as these addons already deliver the link for the file. You can look inside the log from kodi to get the link.

**Comment by claell** [comment]
I just searched around a bit and this seems to fulfil your needs: https://www.tvaddons.ag/genesis-downloads/

**Comment by Wikinaut** [comment]
@claell not sure about "Genesis". It i snot listed in the lsit of available Addons, most likely requires some modifications like adding another repo, and then it is not clear how it works.

**Comment by claell** [comment]
Yes, needs adding either a repo or installing it manually via zip. I don't know, whether it works, but it might be worth a try. But maybe there will be a MediathekView addon developed, which of course would be better.

**Comment by Wikinaut** [comment]
Solution: the available youtube-dl can also be used to download e.g. "Tatort" or "Tagesschau".

**Comment by claell** [comment]
Via context menu?

**Comment by Wikinaut** [comment]
No, unfortunately not via a context menu.

Workflow:

* start a movie e.g. "Tagesschau"
* go to Main Menu entry "Programme" (or, on the remote control: "Anwendungen")
* start "youtube-dl"
* a submenu of "youtube-dl" appears with the entry "Download Currently Playing Video"
* click that menu entry
* download starts after some seconds (be patient)

Prerequisites:
* you must have the "youtube-dl" AddOn installed and
* configured (mainly the directory path where the downloads should go to).

**Comment by Wikinaut** [comment]
...I could not (yet) find a way to **delete** downloaded files, uh..... crappy

**Comment by Wikinaut** [comment]
#### How to delete a file on OSMC

* Main menu > Einstellungen > Dateimanager
* Add "Home Ordner" ```/home/osmc``` > "Ok"

Now you can select files and also delete.

**Comment by Wikinaut** [comment]
@xaverW in https://github.com/raptor2101/Mediathek/issues/67#issuecomment-175225380 the question came up, whether the Filelist url is "static". Perhaps, if you want, please can you answer there ?

**Comment by Wikinaut** [comment]
@xaverW or use his up-to-date atom list http://linkeddata.mro.name/open/tv/mediathek/ardmediathek.de/series/index.opml

**Comment by tuxpoldo** [comment]
Done! See here: https://github.com/mediathekview/plugin.video.mediathekview

;-)
