### ISSUE TITLE
Show "Download verboten" bzw. "Forbidden" (not: "Fehlerhaft") for responsecode 403 Forbidden

### ISSUE THREAD

**Issue by Wikinaut** [xaverW/MediathekView#62]
When you want to download e.g. Tatort outside DACH (Germany/Austria/Switzerland) you might receive a 403.

I suggest that the download panel then shows the correct "403" message, not the general word "fehlerhaft" (column "Fortschritt").

**Comment by claell** [comment]
I like this suggestion, maybe also add the responsecode.

**Comment by criztovyl** [comment]
+1

**Comment by xaverW** [comment]
it should work so, problem is maybe (ORF) that they dont't send 403, they send a video "don't work in your country"
