### ISSUE TITLE
html anyone

### ISSUE THREAD

**Issue by fuller42** [xaverW/MediathekView#63]
i recon the list/filter could be implemented as a simple webpage.
and a lot of ppl could get rid of java.... 

has anyone done this already?

**Comment by lutzhorn** [comment]
The whole application is a Java application. But you are free to port it to a web application. Then you have to answer the question of hosting it.

**Comment by fuller42** [comment]
thought of it as a product which provides an alternate way to access a specific vod-service.
most of the hassle is (imo) getting, maintaining and serving the resource list.

serving some html/js/css that parses and filters the Filmliste-akt.xz from the existing infrastructure and callinging it "MediathekView Thin/Web/Mobile Client" could be a huge win.

**Comment by claell** [comment]
The problem is that there would be a developer needed, who does that.

**Comment by criztovyl** [comment]
http://mediathekdirekt.de/ https://gitlab.com/mediathekdirekt/mediathekdirekt

**Comment by fuller42** [comment]
tyvm
