### ISSUE TITLE
ver.11.555 'Das Programm „MediathekView“ kann nicht geoeffnet werden.'

### ISSUE THREAD

**Issue by macuserguru** [xaverW/MediathekView#66]
I had run ver.10 before and delete it.
Then put ver.11.555 in the program folder as MediathekView.app
I want to start them as in instruction seen - it comes the error:
Das Programm „MediathekView“ kann nicht geöffnet werden.

I test some. If I renamed the program to  MediathekView_11.app it works now.
Strange behavior!?

**Comment by xaverW** [comment]
its known.

http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=1963





Am Fri, 25 Mar 2016 23:19:43 -0700
schrieb macuserguru <notifications@github.com>:

**Comment by macuserguru** [comment]
Curios - if I renamed** MediathekView.app** to** MediathekView_11.app** it works without this trick
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=1963

**Comment by macuserguru** [comment]
Please add this hint here
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=1963
(I am not registered there)
