### ISSUE TITLE
ARD/ZDF livestream low resolution: Opens only first stream in m3u8

### ISSUE THREAD

**Issue by alexara** [xaverW/MediathekView#74]
Hello,

Mediathekview downloads the file: `http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8` which looks like this the one at the end of the post.

Apparently, the first stream link in the file refers to the one with a resolution of 320x176.
This is also the one which is opened in the VLC player when pressed on "play" in Mediathekview -- 
though in Mediathekview "download and play high quality (HD)" was set.

I'm on Ubuntu 16.04 64bit and use Mediathekview 10.865 and VLC 2.2.2

##### `master.m3u8`
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=189000,RESOLUTION=320x176,CODECS="avc1.66.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_189_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=189000,RESOLUTION=320x176,CODECS="avc1.66.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_189_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=436000,RESOLUTION=480x272,CODECS="avc1.66.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_436_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=436000,RESOLUTION=480x272,CODECS="avc1.66.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_436_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=736000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_736_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=736000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_736_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1456000,RESOLUTION=852x480,CODECS="avc1.77.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_1456_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1456000,RESOLUTION=852x480,CODECS="avc1.77.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_1456_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2256000,RESOLUTION=1024x576,CODECS="avc1.77.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_2256_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2256000,RESOLUTION=1024x576,CODECS="avc1.77.30, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_2256_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3056000,RESOLUTION=1280x720,CODECS="avc1.640029, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_3056_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3056000,RESOLUTION=1280x720,CODECS="avc1.640029, mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_3056_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=56000,CODECS="mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_189_a-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=56000,CODECS="mp4a.40.2"
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_189_a-b.m3u8?sd=10&rebase=on
```

**Comment by xaverW** [comment]
thats, what ZDF offers

**Comment by alexara** [comment]
> thats, what ZDF offers

And the ARD, too. So you need to parse the file and grep the correct stream. Isn't that implemented yet? Are PR welcomed in that case?

Alex

**Comment by xaverW** [comment]
"Are PR welcomed in that case?" means?
because of often changes, the streams where searched and added manually, i offer that, was ZDF,.. self offers. I get the stream in VLC in HD.

**Comment by alexara** [comment]
> "Are PR welcomed in that case?" means?

I thought about writing a script to crawl an m3u8 file - but currently I do not have the time anyway.
However, maby that isn't necessary at all, if it already works for you and it only regards me.

>  was ZDF,.. self offers.

What do you mean?

> I get the stream in VLC in HD.

Same for me, if I pick the right one manually from the m3u8 file. 

Just to clarify: 
If you "play" the ARD/ZDF livestream from Mediathekview, VLC opens and plays the HD stream?
Which version of VLC do you use?  Do you have a special setting? Why doesn't do it my VLC 2.2.2?

**Comment by xaverW** [comment]
> Just to clarify:
If you "play" the ARD/ZDF livestream from Mediathekview, VLC opens and plays the HD stream?
Which version of VLC do you use? Do you have a special setting? Why doesn't do it my VLC 2.2.2?

yes with vlc 2.2.4

look at this:
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2010&start=20

**Comment by alexara** [comment]
> look at this:
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2010&start=20

I temporarily installed the VLC 3.0.0 and there it works as expected, so it's not an issue of Mediathekview. Thanks.
