### ISSUE TITLE
Tatort since 3 weeks only from Sender "ORF" ?

### ISSUE THREAD

**Issue by henning** [xaverW/MediathekView#75]
Tatort is shown only from "ORF" since two weeks, and cannot be downloaded in germany or anywhere else as ORF seems to have hard rules about not showing the contents in other countries.

So the movies from the last three sundays are not available.

In http://www.mediathekdirekt.de/ they don't even appear at all.

I'd like to help debugging / solving this issue, but don't really know where to start, a hint would be very much appreciated.

**Comment by xaverW** [comment]
in den letzten 2 Wochen sind Tatorte in folgenden Sendern:
BR, ARD, WDR, SRF, NDR
und auch in: http://www.mediathekdirekt.de
alle in DE abrufbar.

**Comment by henning** [comment]
OK ich habe mal upgedatet und dann ging es.
Sorry.

Aber seltsamerweise sah mit der älteren Version ansonsten alles vollkommen OK aus, es gab auch ganz viele Inhalte, nur exakt die tatorte von den letzten drei Sonntagen waren nicht oder nur über ORF verfügbar, der wiederum download aus DE blockt.

Jetzt geht es. Danke.
