### ISSUE TITLE
Ein Download in Pfade, die Leerzeichen enthalten, ist nicht möglich

### ISSUE THREAD

**Issue by mamuesp** [xaverW/MediathekView#81]
Ich habe ein Volume, dass den Namen "LocalData HD" trägt. Es wird immer versucht, in "LocalData_HD" zu speichern, was natürlich fehlschlägt. Moderne System haben aber keine Probleme mehr mit solchen Pfaden, daher sollte das hier auch so sein.

**Comment by xaverW** [comment]
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1976

in den Einstellungen das Ersetzen von Leerzeichen ausschalten, dann sollte es klappen.

**Comment by xaverW** [comment]
sollte jetzt klappen
