### ISSUE TITLE
Releases bei GitHub hochladen

### ISSUE THREAD

**Issue by schildbach** [xaverW/MediathekView#88]
Sourceforge ist mehrmals damit aufgefallen, hochgeladene Binaries mit Spyware zu infizieren. GitHub selbst bietet die komfortable Möglichkeit, die Binaries an Tags zu hängen – diese tauchen dann im Projekt-Reiter "Releases" auf.

**Comment by xaverW** [comment]
die Tags gibs schon, im Ordner "dist" sind die Binaries dazu. Werde aber bei SF bleiben, ist jetzt so "eingelaufen".

**Comment by blausand** [comment]
Ah, sehr gut zu wissen. Danke!
(Ich fasse Sourceforge auch längst nicht mehr mit der Zange an.)
In `/dist` gibt es allerdings nicht mehr den praktischen grünen `Download…`-Button, nur auf höchster Ebene, also inklusive `/src`.
Wenn ich richtig verstehe, braucht man den gesamten Ordner ´/dist´. Kann man das nicht ohne ´/src´ bekommen?

**Comment by schildbach** [comment]
@xaverW Kannst du dann vielleicht SHA256-Hashes deiner Binaries auf GitHub veröffentlichen? Damit könnte man wenigstens erkennen, wenn mal wieder eine neue Malware von Sourceforge verteilt wird.

**Comment by xaverW** [comment]
bei SF gitbs md5 Hashes, die werden von mir nach dem Upload kontrolliert

**Comment by schildbach** [comment]
So rum funktioniert das nicht. Du musst den Hash an einem _vertrauenswürdigem_ Ort ablegen damit er einen Wert hat, also nicht auf Sourceforge.

Ausserdem gilt MD5 seit langem als geknackt. SHA1 wäre das mindeste, besser SHA256.

**Comment by xaverW** [comment]
das zeigst du mir mal, wie du ein lauffähiges Programm hinbekommst das den gleichen md5 hat
im übrigen ist SHA1 auch vorhanden.

**Comment by xaverW** [comment]
> Angriffe, in denen man Kollisionen zu bereits vorgegebenen Daten findet ("Pre-Image-Angriff") sind dagegen (noch) nicht bekannt, so dass die Sicherheit dieser Algorithmen für Passwortdateien oder zur Verifikation von Software-Paketen z.Zt. nicht zur Disposition steht. Es spricht natürlich trotzdem nichts dagegen, wenn man die Wahl hat auch für diese Zwecke die stärkeren SHA-Algorithmen zu nutzen.

und wenn nichts dagegen spricht, mach ichs halt, dass da Ruhe einkehrt. Im übrigen müsste jemand der ganz sicher gehen will, die Software selbst übersetzen (oder besser noch, selbst schreiben!)

**Comment by xaverW** [comment]
im Ordner dist/Info liegen jetzt die md5 und sha1 Hashes für alle Dateien im dist-Ordner

**Comment by schildbach** [comment]
Danke!
