### ISSUE TITLE
How to install MediathekView Version 12: Instructions for Debian 8 Jessie users

### ISSUE THREAD

**Issue by Wikinaut** [xaverW/MediathekView#92]
Debian 8 users must install openjdk 8 and openjfx to run the MediathekView version 12.

* install openjdk 8

As of 31 July 2015 there is a Java 8 backport. To install it, first add this line at the end of /etc/apt/sources.list:
```
deb http://http.debian.net/debian jessie-backports main
```

Run
```
sudo apt-get update
sudo apt-get install openjdk-8-jre-headless
sudo apt-get install openjdk-8-jdk
```

If Java 7 was installed previously, you will need to change the main 'java' and 'javac' commands to point to Java 8:
```
sudo /usr/sbin/update-java-alternatives -s java-1.8.0-openjdk-amd64
```

Check your java version with 
```
java -version
```

* Install openjfx
```
sudo apt-get install openjfx
```

Sources:
* https://github.com/OpenTreeOfLife/germinator/wiki/Debian-upgrade-notes:-jessie-and-openjdk-8
* https://github.com/xaverW/MediathekView/issues/83#issuecomment-238839974

**Comment by xaverW** [comment]
https://sourceforge.net/p/zdfmediathk/wiki/Linux/#debian-8-gnome

**Comment by Wikinaut** [comment]
Na gut....
