### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by sledz** [xaverW/MediathekView#93]
see attached [mv-log.txt](https://github.com/xaverW/MediathekView/files/477321/mv-log.txt)

System is openSUSE_Leap_42.1. MediathekView is installed using rpm. Problem occured after latest update to

```
Name        : MediathekView
Version     : 11.0
Release     : 18.2
Architecture: noarch
Install Date: Do 25 Aug 2016 20:00:04 CEST
Group       : Productivity/Multimedia/Video/Players
Size        : 5392076
License     : GPL
Signature   : DSA/SHA1, Fr 12 Aug 2016 02:47:30 CEST, Key ID 9df60496523f2a20
Source RPM  : MediathekView-11.0-18.2.src.rpm
Build Date  : Fr 12 Aug 2016 02:47:08 CEST
Build Host  : lamb12
Relocations : (not relocatable)
Vendor      : obs://build.opensuse.org/home:ecsos
URL         : https://github.com/xaverW/MediathekView
Summary     : Durchsucht verschiedene Mediatheken
Description :
Das Programm durchsucht die Mediathek verschiedener Sender (ARD, ZDF, Arte, 3Sat, MDR, NDR, ORF, SF),
lädt Beitrge mit einem Programm eigener Wahl und kann Themen als Abos anlegen
und neue Beiträge automatisch downloaden.
Es gibt auch eine Möglichkeit, Podcast zu verwalten und zu downloaden.
Distribution: home:ecsos / openSUSE_Leap_42.1




```

**Comment by xaverW** [comment]
> .  ###########################################################
.  ###########################################################
.  totalMemory: 16 MB
.  maxMemory: 253 MB
.  freeMemory: 12 MB
.  ###########################################################

aus dem Logfile, ein Blick in die Startdatei "MediathekView__Linux.sh":

>   Wenn der Arbeitsspeicher knapp ist, kann das helfen:
   java -Xms128M -Xmx1G -jar ./MediathekView.jar "$@"

das Programm bekommt vom OS zu wenig Speicher, Startdatei anpassen dann sollte es passen.

**Comment by sledz** [comment]
Thx

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
