### ISSUE TITLE
[Feature Request] -- interface over webservice

### ISSUE THREAD

**Issue by SomeStrangeName** [xaverW/MediathekView#94]
Would be nice to have mediathek view running on a headless machine with a web interface.
For example a raspberry pi with an external disk (USB) and just a connected to ethernet.

Maybe there is some way to use the existing gui code to produce a web frontend.

**Comment by xaverW** [comment]
https://sourceforge.net/p/zdfmediathk/wiki/Anleitung/#auto
this is possible, but a web interface will not come. This would be a completely new project.

**Comment by criztovyl** [comment]
http://mediathekdirekt.de/
