### ISSUE TITLE
Download von adaptiv.wdr.de funktioniert nicht

### ISSUE THREAD

**Issue by manuelbieh** [xaverW/MediathekView#97]
Hi,

beim Versuch die Lokalzeit (oder andere Sendungen) vom Host adaptiv.wdr.de runterzuladen bekomme ich die Meldung, dass der Download fehlerhaft war:
http://imgur.com/fUwJoHV

Das scheint offenbar daran zu liegen, dass dort m3u8 playlists statt der direkten mp4 als URL erkannt wird. Gibt es da eine Lösung? (In meinem Fall konnte ich das jetzt mittels VLC runterladen nachdem ich den Link hatte).

**Comment by xaverW** [comment]
ja, die Programmsets aktualisieren:
https://sourceforge.net/p/zdfmediathk/wiki/FAQ/#alle-downloads-fehlerhaft

**Comment by hurzl** [comment]
Der Download von WDR mit 13.0.1 geht immer noch nicht

**Comment by Nicklas2751** [comment]
@hurzl Bitte schreibe uns dein konkretes Problem im [Forum](https://forum.mediathekview.de/topic/3/anleitung-fehler-melden).

**Comment by hurzl** [comment]
Selbst wenn man die Sets bearbeitet, werden beim nächsten Download die gleichen Parameter genommen!
