### ISSUE TITLE
EOL, wirklich?

### ISSUE THREAD

**Issue by mro** [xaverW/MediathekView#99]
Hallo @xaverW – http://stadt-bremerhaven.de/mediathekview-wird-zum-jahresende-eingestellt/ – stimmt das?

Im Fall erstmal vielen Dank für die Arbeit der vergangenen Jahre!

Als Aufruf in die Runde: Ich wünsche mir OPML+Atom Feeds zum Abonnieren. Wenn mir jemand dabei helfen mag, ich würde gerne in Go einen Scraper/Converter bauen, der die Mediatheken in OpML+Atom konvertiert. Hosting auf einem VPS oder halt eine Github Page. Ergebnis so in der Art von https://github.com/mro/tv-mediathek

Was dann noch fehlt ist

- mehr Mediatheken
- Filterung und Merge von Atom-Feeds für "eigene" Feeds/Abos
- Empfehlung und Installationshilfe für Video Podcatcher (iTunes, Miro, ?)

**Comment by mro** [comment]
P.S.: Das nächste Ticket ist ein Jubiläum!

**Comment by claell** [comment]
Zur Frage: http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2215
Schade, aber da alles ein Hobby ist, durchaus nachvollziehbar.

**Comment by JayBrown** [comment]
Scheint so, wa? Schade. Ich bin auf macOS, und es ist m.W. das einzige Programm, das ich benutzen kann. Noch gebe ich nicht die Hoffnung auf, dass sich jemand findet, der es übernimmt, aber im Zweifelsfall würde mir für die Mediatheken auch ein Command Line Interface reichen. :) Jedenfalls, auch von mir ein dickes Dankeschön!

**Comment by dakira** [comment]
@JayBrown es bleibt noch youtube-dl.

**Comment by fabiang** [comment]
Gibt es solche Projekte auf globaler Ebene? Also so Open-Source-Projekte die das für andere Länder machen? Evtl könnte man sich dort drandongeln und Parser für DE zur Verfügung stellen. Dann hätte man den Vorteil, dass eine globale Community um die Weiterentwicklung kümmern kann, während nur die Deutschen ihre Parser-Libs fixen.

Jedenfalls wäre es für dieses Projekt sinnvoll die Infrastruktur für das Parsen auszulagern und die Informationen per Api zur Verfügung zu stellen.

**Comment by mro** [comment]
@dakira uh - https://github.com/rg3/youtube-dl/ kann ja alle möglichen Mediatheken! Ich dachte das sei nur für YT.

Damit ist (für mich) wahrscheinlich sinnvoller bei youtube-dl mitzuhelfen wenn was nicht geht als etwas neues anzufangen.

Der Wunsch nach RSS/Atom bleibt, ist aber mit https://github.com/mro/tv-mediathek und https://github.com/RSS-Bridge/rss-bridge/blob/master/bridges/Arte7Bridge.php erstmal gut.

**Comment by JayBrown** [comment]
@mro `youtube-dl` ist top, habe ich schon länger installiert, wusste aber ebensowenig, dass es auch für die ÖR-Mediatheken was taugt; man braucht halt nur immer eine aktuelle Liste mit den URLs, also wäre RSS o.ä. nicht unwichtig. Ich denke aber, dass außer mir nur die wenigsten ein CLI benutzen wollen. Ich habe viele Freunde, die MV benutzen, die aber ganz nervös werden, wenn man nur das Terminal startet. ;) Klar, man kann eine Art Software mit GUI drum herum bauen, auf macOS sehr einfach mit einer Kombi aus Shell Script plus AppleScript, oder auch als BitBar-Plugin, aber das wäre dann wieder mal nicht Cross-Platform.
